[project]
authors = ["Sasank Desaraju <sasank.desaraju@ufl.edu>"]
channels = ["nvidia/label/cuda-12.4.0", "nvidia", "conda-forge", "pytorch", "main", "r", "msys2"]
description = "Add a short description here"
name = "turbo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
cuda = {channel="nvidia/label/cuda-12.4.0"}
pytorch = {channel="pytorch"}
torchvision = {channel="pytorch"}
pytorch-cuda = {channel="pytorch"}
python = "3.10.*"
wandb = "0.18.6.*"
# torch = ">=2.0.1"

[pypi-dependencies]
clip = { git = "https://github.com/openai/CLIP.git" }
einops = ">=0.6.1"
numpy = ">=1.24.4"
open-clip-torch = ">=2.20.0"
opencv-python = "==4.6.0.66"
pillow = ">=9.5.0"
scipy = "*"
# scipy = "==1.11.1"
timm = ">=0.9.2"
tokenizers = "*"
torchaudio = ">=2.0.2"
# torchdata = "==0.6.1"
torchmetrics = ">=1.0.1"
tqdm = ">=4.65.0"
transformers = "==4.46.1"
# urllib3 = ">=1.25.4, <1.27"
xformers = ">=0.0.20"
streamlit-keyup = "==0.2.0"
lpips = "*"
clean-fid = "*"
peft = "*"
dominate = "*"
# diffusers = "==0.31.0"
diffusers = "==0.25.1"
# gradio = "==3.43.1"
gradio = "*"
